server {
  listen 80;

  client_max_body_size 0;
  types_hash_max_size 4096;

  location / {
    include uwsgi_params;
    uwsgi_pass pic_app:5000;
    uwsgi_connect_timeout 1200;
    uwsgi_send_timeout 1200;
    uwsgi_read_timeout 1200;
  }
}
