[uwsgi]

module = run:app

strict = true
master = true
lazy-apps = false
enable-threads = true

cheaper-algo = spare 
processes = 10
cheaper = 2
cheaper-initial = 2
cheaper-overload = 5
cheaper-step = 1

max-requests = 10
#max-worker-lifetime = 3600
reload-on-rss = 2048

post-buffering = 2097152
post-buffering-bufsize = 2097152

socket = :5000
gid = 1000
uid = 1000
chmod-socket = 660

auto-procname = true

stats = :9000

http-timeout = 1200
socket-timeout = 1200
harakiri = 1200

vacuum = true
single-interpreter = true

die-on-term = true
need-app = true
